force-app/main/default/objects/Aeroporto__c/Aeroporto__c.object-meta.xml
<CustomObject>
    <label>Aeroporto</label>
    <nameField>
        <label>Aeroporto Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aeroportos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Aeroporto__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estado</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Localizacao__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Estado</value>
        </filterItems>
        <filterItems>
            <field>Localizacao__c.Pertence__c</field>
            <operation>equals</operation>
            <valueField>$Source.Pais__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Localizacao__c</referenceTo>
    <relationshipLabel>Aeroportos (Estado)</relationshipLabel>
    <relationshipName>Aeroportos1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Aeroporto__c/fields/Sigla__c.field-meta.xml
<CustomField>
    <fullName>Sigla__c</fullName>
    <label>Sigla</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Localizacao__c/Localizacao__c.object-meta.xml
<CustomObject>
    <label>Localização</label>
    <nameField>
        <label>Localizacao Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Localizações</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Ticket Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Voo_Ida__c.field-meta.xml
<CustomField>
    <fullName>Voo_Ida__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Voo de Ida</label>
    <referenceTo>Voo__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Voo_Volta__c.field-meta.xml
<CustomField>
    <fullName>Voo_Volta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Voo de Volta</label>
    <referenceTo>Voo__c</referenceTo>
    <relationshipLabel>Tickets (Voo de Volta)</relationshipLabel>
    <relationshipName>Tickets1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Voo__c/Voo__c.object-meta.xml
<CustomObject>
    <label>Voo</label>
    <nameField>
        <displayFormat>V-{0000}</displayFormat>
        <label>Voo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Voos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Voo__c/fields/Aeroporto_Chegada__c.field-meta.xml
<CustomField>
    <fullName>Aeroporto_Chegada__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Aeroporto Chegada</label>
    <referenceTo>Aeroporto__c</referenceTo>
    <relationshipLabel>Voos (Aeroporto Chegada)</relationshipLabel>
    <relationshipName>Voos1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Voo__c/fields/Aeroporto_Partida__c.field-meta.xml
<CustomField>
    <fullName>Aeroporto_Partida__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Aeroporto Partida</label>
    <referenceTo>Aeroporto__c</referenceTo>
    <relationshipLabel>Voos</relationshipLabel>
    <relationshipName>Voos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Voo__c/fields/Assento__c.field-meta.xml
<CustomField>
    <fullName>Assento__c</fullName>
    <label>Assento</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Voo__c/fields/Companhia__c.field-meta.xml
<CustomField>
    <fullName>Companhia__c</fullName>
    <label>Companhia</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Voo__c/fields/Data_Chegada__c.field-meta.xml
<CustomField>
    <fullName>Data_Chegada__c</fullName>
    <label>Data de Chegada</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Voo__c/fields/Hora_de_Chegada__c.field-meta.xml
<CustomField>
    <fullName>Hora_de_Chegada__c</fullName>
    <label>Hora de Chegada</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Voo__c/fields/Hora_de_Partida__c.field-meta.xml
<CustomField>
    <fullName>Hora_de_Partida__c</fullName>
    <label>Hora de Partida</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TicketsController.cls
public with sharing class TicketsController {

    @AuraEnabled(cacheable=true)
    public static List<Aeroporto__c> getAeroportos(String search){

        search += '%';
        List<Aeroporto__c> aeroportos = [SELECT Id, Name, Estado__r.Name, Sigla__c FROM Aeroporto__c WHERE Name LIKE :search OR Estado__r.Name LIKE :search OR Sigla__c LIKE :search];
        return aeroportos;
    }

    public static Date dateParse(String dateString){
        List<String> dt = dateString.split('-');
        Date dateResult = Date.newInstance(Integer.valueof(dt[0]), Integer.valueof(dt[1]), Integer.valueof(dt[2]));

        return dateResult;
    }

    @AuraEnabled(cacheable=true)
    public static List<RetornoVooTO> getVoos(String aeroportoOrigem, String aeroportoDestino, String dataPartida, String dataRetorno){

        Date dtPartida = dateParse(dataPartida);
        Date dtRetorno = dateParse(dataRetorno);
        
        List <Voo__c> voosOrigem = [SELECT Id, Name, Aeroporto_Chegada__r.Sigla__c, Aeroporto_Partida__r.Sigla__c, Assento__c, Companhia__c, Data_Chegada__c, Data_Partida__c, Hora_de_Chegada__c, Hora_de_Partida__c, Valor__c FROM Voo__c WHERE Aeroporto_Chegada__c =: aeroportoDestino AND Aeroporto_Partida__c =: aeroportoOrigem AND Data_Partida__c =: dtPartida ];

        List <Voo__c> voosDestino = [SELECT Id, Name, Aeroporto_Chegada__r.Sigla__c, Aeroporto_Partida__r.Sigla__c, Assento__c, Companhia__c, Data_Chegada__c, Data_Partida__c, Hora_de_Chegada__c, Hora_de_Partida__c, Valor__c FROM Voo__c WHERE Aeroporto_Chegada__c =: aeroportoOrigem AND Aeroporto_Partida__c =: aeroportoDestino AND Data_Partida__c =: dtRetorno];

        List <RetornoVooTO> results = new List<RetornoVooTO>();

        for(Voo__c vooOrigem : voosOrigem){
            for(Voo__c vooDestino : voosDestino){
                results.add(new RetornoVooTO(vooOrigem, vooDestino));
            }
        }
        System.debug('results '+ results);
        return results;
    }

    @AuraEnabled(cacheable=true)
    public static Ticket__c createTicket(String accountId, String vooIdaId, String vooVoltaId){
        Ticket__c ticket = new Ticket__c();
            ticket.Account__c = accountId;
            ticket.Voo_Ida__c = vooIdaId;
            ticket.Voo_Volta__c = vooVoltaId;
        
        insert ticket;

        return ticket;

    }

    public class RetornoVooTO{
        @AuraEnabled
        public Voo__c vooIda;
        @AuraEnabled
        public Voo__c vooVolta;

        public RetornoVooTO(Voo__c vooIda, Voo__c vooVolta){
            this.vooIda = vooIda;
            this.vooVolta = vooVolta;
        }
    }

}